<?php
// $Id$

/**
 * Implementation of hook_init().
 */
function noteresourcejs_init() {
  drupal_add_css(drupal_get_path('module', 'noteresourcejs') . '/css/notes.css');
  drupal_add_js(drupal_get_path('module', 'noteresourcejs') . '/js/notes.js');
}

/**
 * Implementation of hook_default_services_endpoint().
 */
function noteresourcejs_default_services_endpoint() {
  $endpoints = array();

  $endpoint = new stdClass;
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->endpoint = 'notes';
  $endpoint->title = 'Note API';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'js-api';
  $endpoint->authentication = '';
  $endpoint->authentication_settings = array();
  $endpoint->resources = array(
    'note' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 1,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 1,
        ),
        'delete' => array(
          'enabled' => 1,
        ),
        'index' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  $endpoints[] = $endpoint;

  return $endpoints;
}